name: Plugin Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    # Güncellenmiş, doğru Discourse test şablonu yolu:
    uses: discourse/.github/.github/workflows/plugin.yml@main